federation_version: 2
subgraphs:
  astronauts:
    routing_url: http://localhost:5001
    schema:
      file: ./astronauts.graphql
  missions:
    routing_url: http://localhost:5002
    schema:
      file: ./missions.graphql